### ISSUE TITLE
DB seed for users and role

### ISSUE THREAD

**Issue by mrs01dev** [foyzulkarim/mern-boilerplate#7]
Dear Foyzul Karim 
please 
create seed for users and roles
Thanks.

Your name in Arabic
Foyzul : فيض الله 
means : God's gift or God's Excess Giving or  Generous of God 
Karim : كريم
means :Generous

**Comment by foyzulkarim** [comment]
@mrs01dev I have added a proper data seeding process. You can seed data using `npm run db:seed` command. For details, please check our readme file. 
I am closing this issue.
